apiVersion: apps/v1
kind: Deployment
metadata:
  name: moscow-time
spec:
  replicas: 3
  selector:
    matchLabels:
      app: moscow-time
  template:
    metadata:
      labels:
        app: moscow-time
    spec:
      containers:
      - name: python-moscow-time
        image: roukayazaki/roukaya
        ports:
        - containerPort: 5000